# Generated by Django 6.0.4 on 2026-05-06 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_categoria_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('cor', models.CharField(max_length=100, null=True)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('potencia', models.IntegerField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carro', to='ecommerce.categoria')),
            ],
            options={
                'ordering': ['ano'],
            },
        ),
    ]
