# Generated by Django 6.0.4 on 2026-05-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='carros/'),
        ),
    ]
