# Generated by Django 6.0.4 on 2026-05-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_carro_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('notebook', 'Notebook'), ('desktop', 'Desktop'), ('celular', 'Celular'), ('tablet', 'Tablet'), ('monitor', 'Monitor'), ('outro', 'Outro')], max_length=20)),
                ('patrimonio', models.CharField(max_length=30, unique=True)),
                ('responsavel', models.CharField(blank=True, max_length=100)),
                ('setor', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
